server:
  port: 9005


spring:
  application:
    name: vending
  datasource:
    url: jdbc:mysql://localhost:3306/database_finale
    username: root 
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver